In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
vocab_size= 10000 

# One Hot Representation

In [5]:
onehot_repn= [one_hot(words,vocab_size) for words in sent]
onehot_repn

[[9710, 7513, 7597, 7526],
 [9710, 7513, 7597, 2816],
 [9710, 829, 7597, 9402],
 [6320, 9846, 6535, 1612, 4279],
 [6320, 9846, 6535, 1612, 3615],
 [4982, 9710, 9721, 7597, 216],
 [8281, 7324, 6821, 1612]]

# Words Embedding Representation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [9]:
# To make every sentence of equal length.
sent_length=8
embedded_docs=pad_sequences(onehot_repn,padding='pre',maxlen=sent_length)   # PRE- Adds 0 in first.
print(embedded_docs)

[[   0    0    0    0 9710 7513 7597 7526]
 [   0    0    0    0 9710 7513 7597 2816]
 [   0    0    0    0 9710  829 7597 9402]
 [   0    0    0 6320 9846 6535 1612 4279]
 [   0    0    0 6320 9846 6535 1612 3615]
 [   0    0    0 4982 9710 9721 7597  216]
 [   0    0    0    0 8281 7324 6821 1612]]


In [10]:
dim= 10

In [12]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[ 0.0189553   0.01652524 -0.02769233 -0.04887816  0.01678718
    0.00296974 -0.03961126  0.0196339   0.02827123  0.02259532]
  [ 0.0189553   0.01652524 -0.02769233 -0.04887816  0.01678718
    0.00296974 -0.03961126  0.0196339   0.02827123  0.02259532]
  [ 0.0189553   0.01652524 -0.02769233 -0.04887816  0.01678718
    0.00296974 -0.03961126  0.0196339   0.02827123  0.02259532]
  [ 0.0189553   0.01652524 -0.02769233 -0.04887816  0.01678718
    0.00296974 -0.03961126  0.0196339   0.02827123  0.02259532]
  [ 0.02988324  0.0408066   0.00315648  0.00227831  0.00020603
   -0.00859253 -0.01068347 -0.03666557 -0.04828262 -0.04843256]
  [-0.04449592  0.0193052   0.01193569  0.03682724  0.02620352
    0.00219942 -0.03816912 -0.04693292  0.02285231  0.03090413]
  [ 0.01037864  0.02812607 -0.02624342 -0.0313501  -0.02994812
   -0.02408326 -0.0074864   0.04440954 -0.02763649  0.01327476]
  [-0.04928757 -0.03115643 -0.02123207  0.03503015  0.01013801
   -0.02142072 -0.02682975  0.01997188 -0.038008

In [16]:
model.predict(embedded_docs[0])

array([[[ 0.0189553 ,  0.01652524, -0.02769233, -0.04887816,
          0.01678718,  0.00296974, -0.03961126,  0.0196339 ,
          0.02827123,  0.02259532]],

       [[ 0.0189553 ,  0.01652524, -0.02769233, -0.04887816,
          0.01678718,  0.00296974, -0.03961126,  0.0196339 ,
          0.02827123,  0.02259532]],

       [[ 0.0189553 ,  0.01652524, -0.02769233, -0.04887816,
          0.01678718,  0.00296974, -0.03961126,  0.0196339 ,
          0.02827123,  0.02259532]],

       [[ 0.0189553 ,  0.01652524, -0.02769233, -0.04887816,
          0.01678718,  0.00296974, -0.03961126,  0.0196339 ,
          0.02827123,  0.02259532]],

       [[ 0.02988324,  0.0408066 ,  0.00315648,  0.00227831,
          0.00020603, -0.00859253, -0.01068347, -0.03666557,
         -0.04828262, -0.04843256]],

       [[-0.04449592,  0.0193052 ,  0.01193569,  0.03682724,
          0.02620352,  0.00219942, -0.03816912, -0.04693292,
          0.02285231,  0.03090413]],

       [[ 0.01037864,  0.02812607, -0.02