In [1]:
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
# Applying the HAAR cascade algorithm to detect face. If we use the code mentioned in website it will show attribute error.
#face_cascade = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
#eye_cascade = cv.CascadeClassifier('haarcascade_eye.xml')
#error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'
# Therefore use this to call the cascades.
face_cascade = cv.CascadeClassifier(cv.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv.CascadeClassifier(cv.data.haarcascades + 'haarcascade_eye.xml')


In [3]:
# Working Code
def get_required_image(image_path):
    img = cv.imread(image_path)
    if img is None:
        return None
    gray_img = cv.cvtColor(img, cv.COLOR_RGB2GRAY)
    faces = face_cascade.detectMultiScale(gray_img, 1.3, 5)
    for x,y,w,h in faces:
        roi_img = img[y:y+h, x:x+w]
        roi_gray = gray_img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_img)
        print(eyes)
        if len(eyes)<2:
            return None
        else:
            return roi_img

def get_required_image(image_path):
    img = cv.imread(image_path)
    gray_img = cv.cvtColor(img, cv.COLOR_RGB2GRAY)
    face_cascade = cv.CascadeClassifier(cv.data.haarcascades + 'haarcascade_frontalface_default.xml')
    eye_cascade = cv.CascadeClassifier(cv.data.haarcascades + 'haarcascade_eye.xml')
    faces = face_cascade.detectMultiScale(gray_img, 1.3, 5)
    for x,y,w,h in faces:
        roi_img = img[y:y+h, x:x+w]
        roi_gray = gray_img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray)
    if len(eyes) >= 2:
        return(roi_img)

# Sir Code
def get_cropped_image_if_2_eyes(image_path):
    img = cv.imread(image_path)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x,y,w,h) in faces:
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray)
        if len(eyes) >= 2:
            return roi_color

In [4]:
path_to_dataset = './DataSets/'
path_to_cropped = './DataSets/cropped_images/'

In [5]:
import os
img_dirs = []
for entry in os.scandir(path_to_dataset):
    if entry.is_dir():
        img_dirs.append(entry.path)

In [6]:
img_dirs

['./DataSets/.ipynb_checkpoints',
 './DataSets/Bill Gates',
 './DataSets/Elon Musk',
 './DataSets/Jeff Bezos',
 './DataSets/Sundar Pichai']

In [7]:
import shutil
if os.path.exists(path_to_cropped):
     shutil.rmtree(path_to_cropped)
os.mkdir(path_to_cropped)

In [8]:
cropped_image_dirs = []
celebrity_file_names_dict = {}

for img_dir in img_dirs:
    count = 1
    celebrity_name = img_dir.split('/')[-1]
    celebrity_file_names_dict[celebrity_name] = []
    for entry in os.scandir(img_dir):
        roi_color = get_required_image(entry.path)
        if roi_color is not None:
            cropped_folder = path_to_cropped + celebrity_name
            if not os.path.exists(cropped_folder):
                os.makedirs(cropped_folder)
                cropped_image_dirs.append(cropped_folder)
                print("Generating cropped images in folder: ",cropped_folder)
            cropped_file_name = celebrity_name + str(count) + ".png"
            cropped_file_path = cropped_folder + "/" + cropped_file_name
            cv.imwrite(cropped_file_path, roi_color)
            celebrity_file_names_dict[celebrity_name].append(cropped_file_path)
            count += 1
        else:
            continue

()
[[27 55 25 25]]
()
()
()
()
()
[[47 31 20 20]
 [22 18 24 24]]
Generating cropped images in folder:  ./DataSets/cropped_images/Elon Musk
[[15 20 25 25]
 [47 24 22 22]]
()
()
()
[[ 9 13 22 22]]
[[34 23 22 22]]
[[40 18 22 22]
 [10 20 25 25]]
()
()
()
()
[[10 16 23 23]
 [40 20 22 22]]
()
()
()
[[12 21 24 24]
 [37 19 23 23]]
[[16 20 23 23]]
[[19 29 25 25]
 [53 28 25 25]]
[[60 30 26 26]
 [20 31 26 26]
 [10 32 27 27]]
()
()
[[43 19 25 25]
 [10 20 24 24]]
Generating cropped images in folder:  ./DataSets/cropped_images/Jeff Bezos
()
()
[[68 32 33 33]
 [21 40 25 25]]
[[60 27 26 26]
 [23 31 25 25]]
()
()
()
()


In [9]:
celebrity_file_names_dict = {}
for img_dir in cropped_image_dirs:
    celebrity_name = img_dir.split('/')[-1]
    file_list = []
    for entry in os.scandir(img_dir):
        file_list.append(entry.path)
    celebrity_file_names_dict[celebrity_name] = file_list
celebrity_file_names_dict

{'Elon Musk': ['./DataSets/cropped_images/Elon Musk\\Elon Musk1.png',
  './DataSets/cropped_images/Elon Musk\\Elon Musk2.png',
  './DataSets/cropped_images/Elon Musk\\Elon Musk3.png',
  './DataSets/cropped_images/Elon Musk\\Elon Musk4.png',
  './DataSets/cropped_images/Elon Musk\\Elon Musk5.png',
  './DataSets/cropped_images/Elon Musk\\Elon Musk6.png',
  './DataSets/cropped_images/Elon Musk\\Elon Musk7.png'],
 'Jeff Bezos': ['./DataSets/cropped_images/Jeff Bezos\\Jeff Bezos1.png',
  './DataSets/cropped_images/Jeff Bezos\\Jeff Bezos2.png',
  './DataSets/cropped_images/Jeff Bezos\\Jeff Bezos3.png']}

In [10]:
class_dict = {}
count = 0
for celebrity_name in celebrity_file_names_dict.keys():
    class_dict[celebrity_name] = count
    count = count + 1
class_dict

{'Elon Musk': 0, 'Jeff Bezos': 1}

In [11]:
import numpy as np
import pywt   

def w2d(img, mode='haar', level=1):
    imArray = img
    #Datatype conversions
    #convert to grayscale
    imArray = cv.cvtColor( imArray,cv.COLOR_RGB2GRAY )
    #convert to float
    imArray =  np.float32(imArray)   
    imArray /= 255;
    # compute coefficients 
    coeffs=pywt.wavedec2(imArray, mode, level=level)

    #Process Coefficients
    coeffs_H=list(coeffs)  
    coeffs_H[0] *= 0;  

    # reconstruction
    imArray_H=pywt.waverec2(coeffs_H, mode);
    imArray_H *= 255;
    imArray_H =  np.uint8(imArray_H)

    return imArray_H

In [13]:
X, y = [], []
for celebrity_name, training_files in celebrity_file_names_dict.items():
    for training_image in training_files:
        img = cv.imread(training_image)
        scalled_raw_img = cv.resize(img, (32, 32))
        img_har = w2d(img,'db1',5)
        scalled_img_har = cv.resize(img_har, (32, 32))
        combined_img = np.vstack((scalled_raw_img.reshape(32*32*3,1),scalled_img_har.reshape(32*32,1)))
        X.append(combined_img)
        y.append(class_dict[celebrity_name])   

In [14]:
X = np.array(X).reshape(len(X),4096).astype(float)
X.shape

(10, 4096)

In [21]:
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

pipe = Pipeline([('scaler', StandardScaler()), ('svc', SVC(kernel = 'rbf', C = 10))])
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.6666666666666666

In [23]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto',probability=True),
        'params' : {
            'svc__C': [1,10,100,1000],
            'svc__kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'randomforestclassifier__n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'logisticregression__C': [1,5,10]
        }
    }
}

In [24]:
model = SVC()

In [26]:
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [28]:
model.predict(X_test)

array([0, 0, 0])

In [31]:
from sklearn.pipeline import make_pipeline
scores = []
best_estimators = {}
import pandas as pd
for algo, mp in model_params.items():
    pipe = make_pipeline(StandardScaler(), mp['model'])
    clf =  GridSearchCV(pipe, mp['params'], cv=5, return_train_score=False)
    clf.fit(X_train, y_train)
    scores.append({
        'model': algo,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    best_estimators[algo] = clf.best_estimator_
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

C:\Users\kulkg\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
C:\Users\kulkg\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
C:\Users\kulkg\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


model  best_score  \
0                  svm         0.9   
1        random_forest         0.9   
2  logistic_regression         0.7   

                                   best_params  
0       {'svc__C': 1, 'svc__kernel': 'linear'}  
1  {'randomforestclassifier__n_estimators': 1}  
2                 {'logisticregression__C': 1}

In [35]:
model = SVC(kernel='linear', C=1)

In [36]:
model.fit(X_test, y_test)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [37]:
model.score(X_test, y_test)

1.0

In [47]:
image = cv.imread('./DataSets/Image2.jpg')

In [48]:
X = []
scalled_raw_img = cv.resize(image, (32, 32))
img_har = w2d(img,'db1',5)
scalled_img_har = cv.resize(img_har, (32, 32))
combined_img = np.vstack((scalled_raw_img.reshape(32*32*3,1),scalled_img_har.reshape(32*32,1)))
X.append(combined_img)
X = np.array(X).reshape(len(X),4096).astype(float)
model.predict(X)

array([0])